---
version: '2'
services:
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./load_data.sql:/docker-entrypoint.initdb.d/load_data.sql
      - ./data:/docker-entrypoint.initdb.d/data
    environment:
      MYSQL_ROOT_PASSWORD: confluent
      MYSQL_DATABASE: flights
  mysql-admin:
    image: adminer
    depends_on:
      - mysql-db
    restart: always
    ports:
      - "8080:8080"
